// Real Behance projects for Jared Duron - jaredduron
// Source: https://www.behance.net/jaredduron

export const PROJECTS = [
  {
    id: 'john-deere-expo',
    title: 'John Deere EXPERIENCE',
    subtitle: 'Expo Summit 2026',
    client: 'John Deere',
    year: '2026',
    role: 'Videografía · Motion · Edición',
    location: 'Expo Summit',
    category: { es: 'Evento · Corporativo', en: 'Event · Corporate', ca: 'Esdeveniment · Corporatiu' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/7ffff9250562715.Y3JvcCwyNjMzLDIwNTksMCwyODY.jpg',
    behanceUrl: 'https://www.behance.net/gallery/250562715/Evento-The-John-Deere-EXPERIENCE-Expo-Summit-2026',
    description: {
      es: 'Producción audiovisual integral para The John Deere EXPERIENCE en Expo Summit 2026. Motion graphics, animación de social media posts, edición de video y branding para el evento comercial más importante de la marca en la región.',
      en: 'Full audiovisual production for The John Deere EXPERIENCE at Expo Summit 2026. Motion graphics, social media animation, video editing and branding for the brand\'s biggest commercial event in the region.',
      ca: 'Producció audiovisual integral per a The John Deere EXPERIENCE a Expo Summit 2026. Motion graphics, animació, edició de vídeo i branding.',
    },
    tools: ['After Effects', 'Premiere Pro', 'Illustrator', 'Photoshop', 'Media Encoder'],
    tags: ['Event', 'Corporate', 'Motion Graphics', 'Video Editing', 'Branding'],
    gallery: [
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/25cf46250562715.6a21c983b3eb6.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/b4d8bc250562715.6a21c983b53d9.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/6117d0250562715.6a21c983b5c7c.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/ff60a6250562715.6a21c983b60b1.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/621a89250562715.6a21c983b582e.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/252d86250562715.6a21c983b4bb5.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/4d1e4c250562715.6a21c983b4f91.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/0c337b250562715.6a21c983b478d.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/807237250562715.6a21c983b434e.jpg',
    ],
    featured: true,
  },
  {
    id: 'barcelona-city',
    title: 'BARCELONA',
    subtitle: 'La ciudad que no se detiene',
    client: 'Personal',
    year: '2026',
    role: 'Fotografía · Long Exposure',
    location: 'Barcelona',
    category: { es: 'Fotografía · Urbana', en: 'Photography · Urban', ca: 'Fotografia · Urbana' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/a1c41d244810739.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.png',
    behanceUrl: 'https://www.behance.net/gallery/244810739/BARCELONA-La-ciudad-que-no-se-detiene-(Fotografias)',
    description: {
      es: 'Serie fotográfica que captura el movimiento incesante de Barcelona a través de largas exposiciones. Desde el tráfico nocturno hasta los pequeños momentos cotidianos, la serie resalta cómo la energía urbana se convierte en luz, forma y ritmo.',
      en: 'Photographic series capturing the ceaseless movement of Barcelona through long exposures. From night traffic to small everyday moments, the series highlights how urban energy becomes light, form and rhythm.',
      ca: 'Sèrie fotogràfica que captura el moviment incessant de Barcelona a través de llargues exposicions.',
    },
    tools: ['Photoshop', 'Lightroom'],
    tags: ['Photography', 'Barcelona', 'Long Exposure', 'Night', 'Urban'],
    gallery: [
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/4ead92244810739.699f8377afda8.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/b5252f244810739.699f8377b49e9.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/e22a59244810739.699f8377b4194.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/998c9b244810739.699f8377b19cf.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/3d271f244810739.699f8377b05ff.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/8d01ea244810739.699f8377b0b90.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/09633b244810739.699f8377b391e.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/c1d249244810739.699f8377b1179.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/db4172244810739.699f8377b1ff7.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/cf0770244810739.699f8377b526c.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/22b4a5244810739.699f8377b289f.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/9d9bfb244810739.699f8377b305e.png',
    ],
    featured: true,
  },
  {
    id: 'cyberpunk-portraits',
    title: 'Cyberpunk Night Portraits',
    subtitle: 'Retratos urbanos',
    client: 'Personal',
    year: '2026', role: 'Fotografía · Retrato',
    location: 'Barcelona',
    category: { es: 'Fotografía · Retrato', en: 'Photography · Portrait', ca: 'Fotografia · Retrat' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/4e3963250476933.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.png',
    behanceUrl: 'https://www.behance.net/gallery/250476933/Cyberpunk-Night-Portraits',
    description: {
      es: 'Serie de retratos nocturnos con estética cyberpunk: neones, luces urbanas y color grading cinematográfico para explorar la relación entre el ser humano y la ciudad post-industrial.',
      en: 'Night portrait series with cyberpunk aesthetic: neons, urban lights and cinematic color grading to explore the relationship between human and post-industrial city.',
      ca: 'Sèrie de retrats nocturns amb estètica cyberpunk.',
    },
    tools: ['Photoshop', 'Lightroom'],
    tags: ['Portrait', 'Cyberpunk', 'Night Photography', 'Cinematic'],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/4e3963250476933.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.png'],
    featured: false,
  },
  {
    id: 'dior-sauvage',
    title: 'Sauvage de Dior',
    subtitle: 'Exploración de Iluminación y Producto',
    client: 'Dior',
    year: '2026', role: 'Fotografía · Producto',
    location: 'Barcelona',
    category: { es: 'Producto · Comercial', en: 'Product · Commercial', ca: 'Producte · Comercial' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/577086248809117.Y3JvcCwzOTk5LDMxMjgsMCw5NDA.jpg',
    behanceUrl: 'https://www.behance.net/gallery/248809117/Sauvage-de-Dior-Exploracion-de-Iluminacion-y-Producto',
    description: {
      es: 'Exploración de iluminación y bodegón fotográfico para Sauvage de Dior. Un estudio de cómo la luz define el carácter de un producto icónico a través del contraste, la sombra y la textura.',
      en: 'Lighting and still-life exploration for Sauvage de Dior. A study of how light defines the character of an iconic product through contrast, shadow and texture.',
      ca: 'Exploració d\'il·luminació i bodegó fotogràfic per a Sauvage de Dior.',
    },
    tools: ['Photoshop', 'Capture One'],
    tags: ['Product', 'Dior', 'Lighting', 'Commercial', 'Still Life'],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/577086248809117.Y3JvcCwzOTk5LDMxMjgsMCw5NDA.jpg'],
    featured: true,
  },
  {
    id: 'knx-ise',
    title: 'KNX at ISE 2026',
    subtitle: 'Integrated Systems Europe',
    client: 'KNX Association',
    year: '2026', role: 'Cobertura · Evento',
    location: 'Barcelona · Fira',
    category: { es: 'Evento · Internacional', en: 'Event · International', ca: 'Esdeveniment · Internacional' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/79f311247713499.Y3JvcCwxNzA0LDEzMzMsMTQ3LDA.jpg',
    behanceUrl: 'https://www.behance.net/gallery/247713499/KNX-at-ISE-2026',
    description: {
      es: 'Cobertura audiovisual completa para KNX Association en ISE 2026, la feria de referencia mundial de tecnologías AV e integración de sistemas celebrada en Barcelona. Vídeo, fotografía y contenido para redes.',
      en: 'Full audiovisual coverage for KNX Association at ISE 2026, the world\'s reference AV & systems integration trade show in Barcelona. Video, photo and social content.',
      ca: 'Cobertura audiovisual completa per a KNX Association a ISE 2026.',
    },
    tools: ['Premiere Pro', 'After Effects', 'Photoshop'],
    tags: ['Event', 'International', 'Tech', 'Trade Show', 'Barcelona'],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/79f311247713499.Y3JvcCwxNzA0LDEzMzMsMTQ3LDA.jpg'],
    featured: true,
  },
  {
    id: 'light-building-frankfurt',
    title: 'Light + Building 2026',
    subtitle: 'Messe Frankfurt',
    client: 'Messe Frankfurt',
    year: '2026', role: 'Cobertura · Evento',
    location: 'Frankfurt · Germany',
    category: { es: 'Evento · Internacional', en: 'Event · International', ca: 'Esdeveniment · Internacional' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/b75545247711829.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.jpg',
    behanceUrl: 'https://www.behance.net/gallery/247711829/light-building-2026-messe-frankfurt',
    description: {
      es: 'Cobertura audiovisual del evento Light + Building 2026 en Messe Frankfurt, la feria líder mundial de iluminación y building services technology. Producción con equipo cinematográfico para un cliente internacional.',
      en: 'Audiovisual coverage of Light + Building 2026 at Messe Frankfurt, the world\'s leading trade fair for lighting and building services technology.',
      ca: 'Cobertura audiovisual de Light + Building 2026 a Messe Frankfurt.',
    },
    tools: ['Premiere Pro', 'DaVinci Resolve'],
    tags: ['Event', 'International', 'Germany', 'Lighting', 'Architecture'],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/b75545247711829.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.jpg'],
    featured: true,
  },
  {
    id: 'prosperos-podcast',
    title: 'Prósperos Podcast',
    subtitle: 'Podcast production',
    client: 'Prósperos',
    year: '2026', role: 'Dirección · Rodaje · Postproducción',
    location: 'Barcelona',
    category: { es: 'Podcast · Producción', en: 'Podcast · Production', ca: 'Podcast · Producció' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/ef8606247708691.Y3JvcCwxMDgwLDg0NCwwLDEwMQ.jpeg',
    behanceUrl: 'https://www.behance.net/gallery/247708691/Prosperos-Podcast',
    description: {
      es: 'Producción audiovisual completa del podcast Prósperos: setup multicámara, iluminación cinematográfica, dirección, edición y clips verticales para redes sociales.',
      en: 'Full audiovisual production of Prósperos podcast: multi-camera setup, cinematic lighting, directing, editing and vertical clips for social media.',
      ca: 'Producció audiovisual completa del podcast Prósperos.',
    },
    tools: ['Premiere Pro', 'After Effects', 'DaVinci Resolve'],
    tags: ['Podcast', 'Multicam', 'Vertical Content', 'Social'],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/ef8606247708691.Y3JvcCwxMDgwLDg0NCwwLDEwMQ.jpeg'],
    featured: false,
  },
  {
    id: 'wwf-guardianes',
    title: 'Guardianes del Bosque',
    subtitle: 'WWF Honduras',
    client: 'WWF',
    year: '2024', role: 'Dirección · DoP · Documental',
    location: 'Honduras',
    category: { es: 'Documental · ONG', en: 'Documentary · NGO', ca: 'Documental · ONG' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/3a2a86204647323.Y3JvcCw5MDUsNzA4LDE0Nyww.jpg',
    behanceUrl: 'https://www.behance.net/gallery/204647323/Proyecto-Guardianes-del-Bosque-WWF-Honduras',
    description: {
      es: 'Documental para WWF Honduras sobre los Guardianes del Bosque, comunidades locales que protegen los ecosistemas del país. Storytelling humano con enfoque cinematográfico y respeto por la comunidad.',
      en: 'Documentary for WWF Honduras about the Forest Guardians, local communities protecting the country\'s ecosystems. Human storytelling with a cinematic approach.',
      ca: 'Documental per a WWF Honduras sobre els Guardians del Bosc.',
    },
    tools: ['Premiere Pro', 'DaVinci Resolve'],
    tags: ['Documentary', 'WWF', 'NGO', 'Nature', 'Storytelling'],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/3a2a86204647323.Y3JvcCw5MDUsNzA4LDE0Nyww.jpg'],
    featured: true,
  },
  {
    id: 'cortometraje',
    title: 'Lo que me gusta',
    subtitle: 'Cortometraje',
    client: 'Personal',
    year: '2024', role: 'Dirección · Guion · Edición',
    location: 'Honduras',
    category: { es: 'Cortometraje · Ficción', en: 'Short Film · Fiction', ca: 'Curtmetratge · Ficció' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/0657d9227834041.Y3JvcCwxMDgwLDg0NCwwLDI1MQ.jpg',
    behanceUrl: 'https://www.behance.net/gallery/227834041/Cortometraje-Lo-que-me-gusta',
    description: {
      es: 'Cortometraje independiente escrito, dirigido y editado por Jared Duron. Una exploración íntima sobre las pequeñas cosas que dan sentido al día a día.',
      en: 'Independent short film written, directed and edited by Jared Duron. An intimate exploration of the small things that give meaning to everyday life.',
      ca: 'Curtmetratge independent dirigit i editat per Jared Duron.',
    },
    tools: ['Premiere Pro', 'DaVinci Resolve'],
    tags: ['Short Film', 'Fiction', 'Directing', 'Independent'],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/0657d9227834041.Y3JvcCwxMDgwLDg0NCwwLDI1MQ.jpg'],
    featured: false,
  },
  {
    id: 'fotografia-producto',
    title: 'Fotografía de Producto',
    subtitle: 'Commercial Still Life',
    client: 'Various',
    year: '2024', role: 'Fotografía Comercial',
    location: 'Barcelona',
    category: { es: 'Producto · Comercial', en: 'Product · Commercial', ca: 'Producte · Comercial' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/160dfe228928107.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.jpg',
    behanceUrl: 'https://www.behance.net/gallery/228928107/Fotografia-de-producto',
    description: {
      es: 'Selección de trabajos de fotografía de producto para marcas: composición, iluminación de estudio y retoque cinematográfico. Desde 50 USD por producto.',
      en: 'Selection of product photography works for brands: composition, studio lighting and cinematic retouching. From $50 per product.',
      ca: 'Selecció de treballs de fotografia de producte.',
    },
    tools: ['Capture One', 'Photoshop'],
    tags: ['Product', 'Commercial', 'Studio', 'Still Life'],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/160dfe228928107.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.jpg'],
    featured: false,
  },
  {
    id: 'miniso',
    title: 'Miniso',
    subtitle: 'Brand Content',
    client: 'Miniso',
    year: '2023', role: 'Videografía · Fotografía',
    location: 'Honduras',
    category: { es: 'Marca · Retail', en: 'Brand · Retail', ca: 'Marca · Retail' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/44a684171064439.Y3JvcCw1MDAxLDM5MTEsMCww.png',
    behanceUrl: 'https://www.behance.net/gallery/171064439/Miniso',
    description: {
      es: 'Contenido audiovisual y fotográfico para Miniso: campañas retail, product shots y contenido para redes sociales con lenguaje pop y color grading vibrante.',
      en: 'Audiovisual and photo content for Miniso: retail campaigns, product shots and social media content with pop language and vibrant color grading.',
      ca: 'Contingut audiovisual i fotogràfic per a Miniso.',
    },
    tools: ['Premiere Pro', 'Photoshop', 'After Effects'],
    tags: ['Retail', 'Brand', 'Commercial', 'Social Media'],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/44a684171064439.Y3JvcCw1MDAxLDM5MTEsMCww.png'],
    featured: false,
  },
  {
    id: 'fotomontaje-epico',
    title: 'Fotomontaje Épico',
    subtitle: 'Compositing & Retouch',
    client: 'Personal',
    year: '2024', role: 'Composición · Retoque',
    location: 'Barcelona',
    category: { es: 'Retoque · Compositing', en: 'Retouch · Compositing', ca: 'Retoc · Compositing' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/a13809228927969.Y3JvcCwzNTA4LDI3NDMsMCwxMTEx.jpg',
    behanceUrl: 'https://www.behance.net/gallery/228927969/Fotomontaje-Epico',
    description: {
      es: 'Fotomontaje épico con composición avanzada, retoque digital y color grading cinematográfico. Un ejercicio visual entre la fotografía y el arte digital.',
      en: 'Epic photomontage with advanced compositing, digital retouching and cinematic color grading.',
      ca: 'Fotomuntatge èpic amb composició avançada.',
    },
    tools: ['Photoshop'],
    tags: ['Compositing', 'Retouch', 'Digital Art'],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/a13809228927969.Y3JvcCwzNTA4LDI3NDMsMCwxMTEx.jpg'],
    featured: false,
  },
]

export const REAL_CLIENTS = [
  'JOHN DEERE', 'DIOR', 'WWF', 'KNX', 'MESSE FRANKFURT', 'MINISO',
  'ISE BARCELONA', 'PRÓSPEROS', 'REGAL SPRINGS', 'ACERTA', 'PUSH DIGITAL', 'LIGHT + BUILDING',
]

export const BLOG_POSTS = [
  {
    slug: 'como-elegir-filmmaker-barcelona',
    date: '2026-06-01',
    read: '6 min',
    category: { es: 'Guía', en: 'Guide', ca: 'Guia' },
    cover: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/4ead92244810739.699f8377afda8.png',
    title: {
      es: 'Cómo elegir un filmmaker en Barcelona: guía completa para marcas',
      en: 'How to choose a filmmaker in Barcelona: a complete guide for brands',
      ca: 'Com triar un filmmaker a Barcelona: guia completa per a marques',
    },
    excerpt: {
      es: 'Cinco criterios clave para escoger el filmmaker adecuado para tu marca en Barcelona: portfolio, workflow, equipo, referencias y capacidad de dirección.',
      en: 'Five key criteria to choose the right filmmaker for your brand in Barcelona: portfolio, workflow, gear, references and directing skills.',
      ca: 'Cinc criteris clau per triar el filmmaker adequat per a la teva marca a Barcelona.',
    },
  },
  {
    slug: 'produccion-audiovisual-empresas',
    date: '2026-05-18',
    read: '8 min',
    category: { es: 'Estrategia', en: 'Strategy', ca: 'Estratègia' },
    cover: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/25cf46250562715.6a21c983b3eb6.jpg',
    title: {
      es: 'Producción audiovisual para empresas: qué esperar en 2026',
      en: 'Corporate video production: what to expect in 2026',
      ca: 'Producció audiovisual per a empreses: què esperar el 2026',
    },
    excerpt: {
      es: 'Del brief al máster final: cómo estructurar una producción audiovisual corporativa que combine narrativa cinematográfica y objetivos de negocio medibles.',
      en: 'From brief to final master: how to structure a corporate video production that combines cinematic narrative and measurable business goals.',
      ca: 'Com estructurar una producció audiovisual corporativa.',
    },
  },
  {
    slug: 'imagen-marca-video',
    date: '2026-04-22',
    read: '5 min',
    category: { es: 'Branding', en: 'Branding', ca: 'Branding' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/577086248809117.Y3JvcCwzOTk5LDMxMjgsMCw5NDA.jpg',
    title: {
      es: 'Cómo mejorar la imagen de una marca con vídeo cinematográfico',
      en: 'How to improve a brand\'s image with cinematic video',
      ca: 'Com millorar la imatge d\'una marca amb vídeo cinematogràfic',
    },
    excerpt: {
      es: 'Tres pilares para que el vídeo eleve tu marca: consistencia visual, storytelling emocional y una dirección de fotografía coherente con el posicionamiento.',
      en: 'Three pillars to make video elevate your brand: visual consistency, emotional storytelling and DoP aligned with positioning.',
      ca: 'Tres pilars perquè el vídeo elevi la teva marca.',
    },
  },
  {
    slug: 'errores-video-corporativo',
    date: '2026-03-14',
    read: '7 min',
    category: { es: 'Errores comunes', en: 'Common Mistakes', ca: 'Errors comuns' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/79f311247713499.Y3JvcCwxNzA0LDEzMzMsMTQ3LDA.jpg',
    title: {
      es: 'Los 7 errores más comunes en vídeos corporativos (y cómo evitarlos)',
      en: 'The 7 most common mistakes in corporate videos (and how to avoid them)',
      ca: 'Els 7 errors més comuns en vídeos corporatius',
    },
    excerpt: {
      es: 'Guiones sin arco narrativo, audio descuidado, iluminación plana... una lista práctica para no repetir los errores clásicos del vídeo corporativo.',
      en: 'Scripts without narrative arc, careless audio, flat lighting... a practical list to avoid the classic mistakes.',
      ca: 'Una llista pràctica per no repetir els errors clàssics.',
    },
  },
  {
    slug: 'meta-ads-anuncios',
    date: '2026-02-08',
    read: '6 min',
    category: { es: 'Publicidad', en: 'Advertising', ca: 'Publicitat' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/ef8606247708691.Y3JvcCwxMDgwLDg0NCwwLDEwMQ.jpeg',
    title: {
      es: 'Consejos para anuncios de Meta Ads que sí convierten',
      en: 'Tips for Meta Ads that actually convert',
      ca: 'Consells per a anuncis de Meta Ads que converteixen',
    },
    excerpt: {
      es: 'Hook en los primeros 3 segundos, formato vertical nativo, jerarquía visual clara y adaptación por plataforma: el checklist definitivo.',
      en: 'Hook in the first 3 seconds, native vertical format, clear visual hierarchy and per-platform adaptation.',
      ca: 'Ganxo en els primers 3 segons, format vertical natiu i jerarquia visual clara.',
    },
  },
  {
    slug: 'produccion-redes-sociales',
    date: '2026-01-20',
    read: '5 min',
    category: { es: 'Social Media', en: 'Social Media', ca: 'Xarxes' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/4e3963250476933.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.png',
    title: {
      es: 'Producción para redes sociales: el nuevo lenguaje de marca',
      en: 'Production for social media: the new brand language',
      ca: 'Producció per a xarxes socials: el nou llenguatge de marca',
    },
    excerpt: {
      es: 'Cómo diseñar un pipeline de contenido social que mantenga la calidad cinematográfica y sea sostenible en volumen mensual.',
      en: 'How to design a social content pipeline that keeps cinematic quality and is sustainable at monthly volume.',
      ca: 'Com dissenyar un pipeline de contingut social sostenible.',
    },
  },
]
