// Real Behance projects for Jared Duron - jaredduron
// Source: https://www.behance.net/jaredduron

export const PROJECTS = [
  {
    id: 'pallapupas-videos',
    title: 'Pallapupas',
    subtitle: 'Videos para ONG sanitaria',
    client: 'Pallapupas',
    year: '2025–2026',
    role: 'Grabación · Edición · Postproducción',
    location: 'Barcelona',
    type: 'video',
    category: { es: 'ONG · Video social', en: 'NGO · Social video', ca: 'ONG · Video social' },
    cover: 'https://img.youtube.com/vi/lt0GBfbRSUM/maxresdefault.jpg',
    description: {
      es: 'Piezas audiovisuales para Pallapupas, entidad de payasos de hospital que trabaja para reducir el miedo y la ansiedad hospitalaria desde la cura emocional. En el proyecto se incluyen videos grabados y editados para la organización, además de una pieza reciente en la que realicé la edición.',
      en: 'Audiovisual pieces for Pallapupas, a hospital clown organization working to reduce fear and anxiety in healthcare spaces through emotional care. The project includes videos filmed and edited for the organization, plus a recent piece focused on editing.',
      ca: 'Peces audiovisuals per a Pallapupas, entitat de pallassos d’hospital que treballa per reduir la por i l’ansietat hospitalària des de la cura emocional. El projecte inclou vídeos gravats i editats per a l’organització, a més d’una peça recent centrada en l’edició.',
    },
    tools: ['Premiere Pro', 'DaVinci Resolve'],
    tags: ['Pallapupas', 'ONG', 'Healthcare', 'Social Video', 'Barcelona'],
    videoEmbeds: [
      'https://www.youtube.com/embed/lt0GBfbRSUM?si=RwgINVOLTJ5ce8Qt',
      'https://www.youtube.com/embed/eflsrSiaC4A?si=kgOsGJpxpTZgedHw',
    ],
    gallery: ['https://img.youtube.com/vi/lt0GBfbRSUM/maxresdefault.jpg'],
    featured: true,
    hideBehancePreview: true,
  },
  {
    id: 'cortometraje',
    title: 'Lo que me gusta',
    subtitle: 'Cortometraje',
    client: 'Personal',
    year: '2024', role: 'Dirección · Guion · Edición',
    location: 'Barcelona',
    category: { es: 'Cortometraje · Ficción', en: 'Short Film · Fiction', ca: 'Curtmetratge · Ficció' },
    cover: 'https://img.youtube.com/vi/hmC-gPI-KZQ/maxresdefault.jpg',
    description: {
      es: 'Cortometraje independiente escrito, dirigido y editado por Jared Duron. Una exploración íntima sobre las pequeñas cosas que dan sentido al día a día.',
      en: 'Independent short film written, directed and edited by Jared Duron. An intimate exploration of the small things that give meaning to everyday life.',
      ca: 'Curtmetratge independent dirigit i editat per Jared Duron.',
    },
    tools: ['Premiere Pro', 'DaVinci Resolve'],
    tags: ['Short Film', 'Fiction', 'Directing', 'Independent'],
    videoEmbeds: ['https://www.youtube.com/embed/hmC-gPI-KZQ?si=hjFHc-Qpkf6cpxXx'],
    gallery: ['https://img.youtube.com/vi/hmC-gPI-KZQ/maxresdefault.jpg'],
    featured: true,
    hideBehancePreview: true,
  },
  {
    id: 'el-agua-es-lo-que-nos-une',
    title: 'Documental: El agua es lo que nos une',
    subtitle: 'Documental',
    client: 'Documental',
    year: '2024',
    role: 'Dirección · Cinematografía · Edición',
    location: 'Honduras',
    type: 'video',
    category: { es: 'Documental', en: 'Documentary', ca: 'Documental' },
    cover: 'https://img.youtube.com/vi/ZXvo2sYwtho/maxresdefault.jpg',
    description: {
      es: 'Documental audiovisual sobre la importancia del agua como elemento que conecta comunidades, territorios e historias humanas.',
      en: 'Audiovisual documentary on the importance of water as an element connecting communities, territories and human stories.',
      ca: 'Documental audiovisual sobre la importancia de l’aigua com a element que connecta comunitats, territoris i històries humanes.',
    },
    tools: ['Premiere Pro', 'DaVinci Resolve'],
    tags: ['Documentary', 'Water', 'Storytelling', 'Human Stories'],
    videoEmbeds: ['https://www.youtube.com/embed/ZXvo2sYwtho?si=HkepDJUxE1Aha18x'],
    gallery: ['https://img.youtube.com/vi/ZXvo2sYwtho/maxresdefault.jpg'],
    featured: true,
    hideBehancePreview: true,
  },
  {
    id: 'knx-light-building-video',
    title: 'KNX Light + Building',
    subtitle: 'Video corporativo / tecnología',
    client: 'KNX',
    year: '2026',
    role: 'Dirección · Videografía · Edición',
    location: 'Frankfurt · Germany',
    type: 'video',
    category: { es: 'Video corporativo · Tecnología', en: 'Corporate video · Technology', ca: 'Video corporatiu · Tecnologia' },
    cover: 'https://img.youtube.com/vi/HhagYnQZWNY/maxresdefault.jpg',
    description: {
      es: 'Pieza audiovisual sobre tecnología, automatización e iluminación inteligente dentro del contexto KNX Light + Building.',
      en: 'Audiovisual piece about technology, automation and intelligent lighting within the KNX Light + Building context.',
      ca: 'Peça audiovisual sobre tecnologia, automatització i il·luminació intel·ligent dins del context KNX Light + Building.',
    },
    tools: ['Premiere Pro', 'After Effects', 'DaVinci Resolve'],
    tags: ['KNX', 'Technology', 'Corporate Video', 'Lighting'],
    videoEmbeds: [
      'https://www.youtube.com/embed/HhagYnQZWNY?si=LcERU6GUq-CbbVTc',
      'https://www.youtube.com/embed/eiGPBrlv-TM?si=u-scIh4eHxmLtoco',
    ],
    gallery: ['https://img.youtube.com/vi/HhagYnQZWNY/maxresdefault.jpg'],
    featured: true,
    hideBehancePreview: true,
  },
  {
    id: 'guardianes-de-bosque-video',
    title: 'Guardianes de bosque',
    subtitle: 'Documental / naturaleza',
    client: 'Documental',
    year: '2024',
    role: 'Dirección · Documental · Edición',
    location: 'Honduras',
    type: 'video',
    category: { es: 'Documental · Naturaleza', en: 'Documentary · Nature', ca: 'Documental · Natura' },
    cover: 'https://img.youtube.com/vi/c62ELVPCG84/maxresdefault.jpg',
    description: {
      es: 'Proyecto audiovisual con enfoque documental sobre la protección del bosque, la relación con el entorno natural y las personas que lo cuidan.',
      en: 'Audiovisual project with a documentary approach to forest protection, the relationship with the natural environment and the people who care for it.',
      ca: 'Projecte audiovisual amb enfocament documental sobre la protecció del bosc, la relació amb l’entorn natural i les persones que el cuiden.',
    },
    tools: ['Premiere Pro', 'DaVinci Resolve'],
    tags: ['Documentary', 'Nature', 'Forest', 'Environmental'],
    videoEmbeds: ['https://www.youtube.com/embed/c62ELVPCG84?si=sfHTUGDHxPfnYCmd'],
    gallery: ['https://img.youtube.com/vi/c62ELVPCG84/maxresdefault.jpg'],
    featured: true,
    hideBehancePreview: true,
  },
  {
    id: 'the-last-of-us-reimagined-scene',
    title: 'The Last of Us — Reimagined Scene',
    subtitle: 'Escena dirigida / ficción',
    client: 'Personal',
    year: '2024',
    role: 'Dirección · Puesta en escena · Edición',
    location: 'Barcelona',
    type: 'video',
    category: { es: 'Escena dirigida · Ficción', en: 'Directed scene · Fiction', ca: 'Escena dirigida · Ficció' },
    cover: 'https://img.youtube.com/vi/KuD3-s8xR3M/maxresdefault.jpg',
    description: {
      es: 'Escena de ficción dirigida como ejercicio de reimaginación cinematográfica inspirada en el inicio de The Last of Us, reinterpretada con una iluminación, atmósfera y contexto visual propios. No es un proyecto oficial.',
      en: 'Fiction scene directed as a cinematic reimagining exercise inspired by the beginning of The Last of Us, reinterpreted with its own lighting, atmosphere and visual context. This is not an official project.',
      ca: 'Escena de ficció dirigida com a exercici de reimaginació cinematogràfica inspirada en l’inici de The Last of Us, reinterpretada amb il·luminació, atmosfera i context visual propis. No és un projecte oficial.',
    },
    tools: ['Premiere Pro', 'DaVinci Resolve'],
    tags: ['Fiction', 'Directed Scene', 'Cinematic Exercise', 'Reimagined'],
    videoEmbeds: ['https://www.youtube.com/embed/KuD3-s8xR3M?si=fGahGpI28Th-kmpC'],
    gallery: ['https://img.youtube.com/vi/KuD3-s8xR3M/maxresdefault.jpg'],
    featured: true,
    hideBehancePreview: true,
  },
  {
    id: 'john-deere-expo',
    title: 'John Deere EXPERIENCE',
    subtitle: 'Expo Summit 2026',
    client: 'John Deere',
    year: '2026',
    role: 'Videografía · Motion · Edición',
    location: 'Expo Summit',
    category: { es: 'Evento · Corporativo', en: 'Event · Corporate', ca: 'Esdeveniment · Corporatiu' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/7ffff9250562715.Y3JvcCwyNjMzLDIwNTksMCwyODY.jpg',
    behanceUrl: 'https://www.behance.net/gallery/250562715/Evento-The-John-Deere-EXPERIENCE-Expo-Summit-2026',
    description: {
      es: 'Producción audiovisual integral para The John Deere EXPERIENCE en Expo Summit 2026. Motion graphics, animación de social media posts, edición de video y branding para el evento comercial más importante de la marca en la región.',
      en: 'Full audiovisual production for The John Deere EXPERIENCE at Expo Summit 2026. Motion graphics, social media animation, video editing and branding for the brand\'s biggest commercial event in the region.',
      ca: 'Producció audiovisual integral per a The John Deere EXPERIENCE a Expo Summit 2026. Motion graphics, animació, edició de vídeo i branding.',
    },
    tools: ['After Effects', 'Premiere Pro', 'Illustrator', 'Photoshop', 'Media Encoder'],
    tags: ['Event', 'Corporate', 'Motion Graphics', 'Video Editing', 'Branding'],
    gallery: [
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/25cf46250562715.6a21c983b3eb6.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/b4d8bc250562715.6a21c983b53d9.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/6117d0250562715.6a21c983b5c7c.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/ff60a6250562715.6a21c983b60b1.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/621a89250562715.6a21c983b582e.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/252d86250562715.6a21c983b4bb5.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/4d1e4c250562715.6a21c983b4f91.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/0c337b250562715.6a21c983b478d.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/807237250562715.6a21c983b434e.jpg',
    ],
    featured: true,
  },
  {
    id: 'barcelona-city',
    title: 'BARCELONA',
    subtitle: 'La ciudad que no se detiene',
    client: 'Personal',
    year: '2026',
    role: 'Fotografía · Long Exposure',
    location: 'Barcelona',
    type: 'photo',
    category: { es: 'Fotografía · Urbana', en: 'Photography · Urban', ca: 'Fotografia · Urbana' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/a1c41d244810739.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.png',
    behanceUrl: 'https://www.behance.net/gallery/244810739/BARCELONA-La-ciudad-que-no-se-detiene-(Fotografias)',
    description: {
      es: 'Serie fotográfica que captura el movimiento incesante de Barcelona a través de largas exposiciones. Desde el tráfico nocturno hasta los pequeños momentos cotidianos, la serie resalta cómo la energía urbana se convierte en luz, forma y ritmo.',
      en: 'Photographic series capturing the ceaseless movement of Barcelona through long exposures. From night traffic to small everyday moments, the series highlights how urban energy becomes light, form and rhythm.',
      ca: 'Sèrie fotogràfica que captura el moviment incessant de Barcelona a través de llargues exposicions.',
    },
    tools: ['Photoshop', 'Lightroom'],
    tags: ['Photography', 'Barcelona', 'Long Exposure', 'Night', 'Urban'],
    gallery: [
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/4ead92244810739.699f8377afda8.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/b5252f244810739.699f8377b49e9.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/e22a59244810739.699f8377b4194.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/998c9b244810739.699f8377b19cf.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/3d271f244810739.699f8377b05ff.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/8d01ea244810739.699f8377b0b90.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/09633b244810739.699f8377b391e.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/c1d249244810739.699f8377b1179.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/db4172244810739.699f8377b1ff7.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/cf0770244810739.699f8377b526c.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/22b4a5244810739.699f8377b289f.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/9d9bfb244810739.699f8377b305e.png',
    ],
    featured: true,
  },
  {
    id: 'cyberpunk-portraits',
    title: 'Cyberpunk Night Portraits',
    subtitle: 'Retratos urbanos',
    client: 'Personal',
    year: '2026', role: 'Fotografía · Retrato',
    location: 'Barcelona',
    type: 'photo',
    category: { es: 'Fotografía · Retrato', en: 'Photography · Portrait', ca: 'Fotografia · Retrat' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/4e3963250476933.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.png',
    behanceUrl: 'https://www.behance.net/gallery/250476933/Cyberpunk-Night-Portraits',
    description: {
      es: 'Serie de retratos nocturnos con estética cyberpunk: neones, luces urbanas y color grading cinematográfico para explorar la relación entre el ser humano y la ciudad post-industrial.',
      en: 'Night portrait series with cyberpunk aesthetic: neons, urban lights and cinematic color grading to explore the relationship between human and post-industrial city.',
      ca: 'Sèrie de retrats nocturns amb estètica cyberpunk.',
    },
    tools: ['Photoshop', 'Lightroom'],
    tags: ['Portrait', 'Cyberpunk', 'Night Photography', 'Cinematic'],
    gallery: [
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/25a5b3250476933.6a20204ae8928.png',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/760e2a250476933.6a20204aea4ed.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/93042e250476933.6a20204aeb1bd.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/0f3518250476933.6a20204ae9285.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/33c9a8250476933.6a20204ae9bac.jpg',
    ],
    featured: false,
  },
  {
    id: 'knx-ise',
    title: 'KNX at ISE 2026',
    subtitle: 'Integrated Systems Europe',
    client: 'KNX Association',
    year: '2026', role: 'Cobertura · Evento',
    location: 'Barcelona · Fira',
    category: { es: 'Evento · Internacional', en: 'Event · International', ca: 'Esdeveniment · Internacional' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/79f311247713499.Y3JvcCwxNzA0LDEzMzMsMTQ3LDA.jpg',
    behanceUrl: 'https://www.behance.net/gallery/247713499/KNX-at-ISE-2026',
    description: {
      es: 'Cobertura audiovisual completa para KNX Association en ISE 2026, la feria de referencia mundial de tecnologías AV e integración de sistemas celebrada en Barcelona. Vídeo, fotografía y contenido para redes.',
      en: 'Full audiovisual coverage for KNX Association at ISE 2026, the world\'s reference AV & systems integration trade show in Barcelona. Video, photo and social content.',
      ca: 'Cobertura audiovisual completa per a KNX Association a ISE 2026.',
    },
    tools: ['Premiere Pro', 'After Effects', 'Photoshop'],
    tags: ['Event', 'International', 'Tech', 'Trade Show', 'Barcelona'],
    videoEmbeds: [
      'https://www.youtube.com/embed/oIb1rTG9Js4?si=Y5_hVP5lu-fR9sb-',
      'https://www.youtube.com/embed/jtFMBOcLJ7w?si=ggZzHoGkk7FemFaj',
    ],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/79f311247713499.Y3JvcCwxNzA0LDEzMzMsMTQ3LDA.jpg'],
    featured: true,
  },
  {
    id: 'prosperos-podcast',
    title: 'Prósperos Podcast',
    subtitle: 'Podcast production',
    client: 'Prósperos',
    year: '2026', role: 'Dirección · Rodaje · Postproducción',
    location: 'Barcelona',
    category: { es: 'Podcast · Producción', en: 'Podcast · Production', ca: 'Podcast · Producció' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/ef8606247708691.Y3JvcCwxMDgwLDg0NCwwLDEwMQ.jpeg',
    behanceUrl: 'https://www.behance.net/gallery/247708691/Prosperos-Podcast',
    description: {
      es: 'Producción audiovisual completa del podcast Prósperos: setup multicámara, iluminación cinematográfica, dirección, edición y clips verticales para redes sociales.',
      en: 'Full audiovisual production of Prósperos podcast: multi-camera setup, cinematic lighting, directing, editing and vertical clips for social media.',
      ca: 'Producció audiovisual completa del podcast Prósperos.',
    },
    tools: ['Premiere Pro', 'After Effects', 'DaVinci Resolve'],
    tags: ['Podcast', 'Multicam', 'Vertical Content', 'Social'],
    videoEmbeds: [
      'https://www.youtube.com/embed/9FaunlMl210?si=ylzd6ABPX-L5PnzP',
      'https://www.youtube.com/embed/vkfPTiybQv0?si=iK2JDyZdhJmMjiRF',
    ],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/ef8606247708691.Y3JvcCwxMDgwLDg0NCwwLDEwMQ.jpeg'],
    featured: false,
  },
  {
    id: 'fotografia-producto',
    title: 'Fotografía de Producto',
    subtitle: 'Commercial Still Life',
    client: 'Various',
    year: '2024', role: 'Fotografía Comercial',
    location: 'Barcelona',
    type: 'photo',
    category: { es: 'Producto · Comercial', en: 'Product · Commercial', ca: 'Producte · Comercial' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/160dfe228928107.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.jpg',
    behanceUrl: 'https://www.behance.net/gallery/228928107/Fotografia-de-producto',
    description: {
      es: 'Selección de trabajos de fotografía de producto para marcas: composición, iluminación de estudio y retoque cinematográfico. Desde 50 USD por producto.',
      en: 'Selection of product photography works for brands: composition, studio lighting and cinematic retouching. From $50 per product.',
      ca: 'Selecció de treballs de fotografia de producte.',
    },
    tools: ['Capture One', 'Photoshop'],
    tags: ['Product', 'Commercial', 'Studio', 'Still Life'],
    gallery: [
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/e7dfe6228928107.685bb807366a4.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/81f2f6228928107.685bb8073569b.jpg',
      'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/0a9b92228928107.685bb80735f4e.jpg',
    ],
    featured: false,
  },
  {
    id: 'miniso',
    title: 'Miniso',
    subtitle: 'Brand Content',
    client: 'Miniso',
    year: '2023', role: 'Videografía · Fotografía',
    location: 'Honduras',
    category: { es: 'Marca · Retail', en: 'Brand · Retail', ca: 'Marca · Retail' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/44a684171064439.Y3JvcCw1MDAxLDM5MTEsMCww.png',
    behanceUrl: 'https://www.behance.net/gallery/171064439/Miniso',
    description: {
      es: 'Contenido audiovisual y fotográfico para Miniso: campañas retail, product shots y contenido para redes sociales con lenguaje pop y color grading vibrante.',
      en: 'Audiovisual and photo content for Miniso: retail campaigns, product shots and social media content with pop language and vibrant color grading.',
      ca: 'Contingut audiovisual i fotogràfic per a Miniso.',
    },
    tools: ['Premiere Pro', 'Photoshop', 'After Effects'],
    tags: ['Retail', 'Brand', 'Commercial', 'Social Media'],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/44a684171064439.Y3JvcCw1MDAxLDM5MTEsMCww.png'],
    featured: false,
  },
  {
    id: 'fotomontaje-epico',
    title: 'Fotomontaje Épico',
    subtitle: 'Compositing & Retouch',
    client: 'Personal',
    year: '2024', role: 'Composición · Retoque',
    location: 'Barcelona',
    type: 'photo',
    category: { es: 'Retoque · Compositing', en: 'Retouch · Compositing', ca: 'Retoc · Compositing' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/a13809228927969.Y3JvcCwzNTA4LDI3NDMsMCwxMTEx.jpg',
    behanceUrl: 'https://www.behance.net/gallery/228927969/Fotomontaje-Epico',
    description: {
      es: 'Fotomontaje épico con composición avanzada, retoque digital y color grading cinematográfico. Un ejercicio visual entre la fotografía y el arte digital.',
      en: 'Epic photomontage with advanced compositing, digital retouching and cinematic color grading.',
      ca: 'Fotomuntatge èpic amb composició avançada.',
    },
    tools: ['Photoshop'],
    tags: ['Compositing', 'Retouch', 'Digital Art'],
    gallery: ['https://mir-s3-cdn-cf.behance.net/projects/404/a13809228927969.Y3JvcCwzNTA4LDI3NDMsMCwxMTEx.jpg'],
    featured: false,
  },
]

export const REAL_CLIENTS = [
  'PALLAPUPAS', 'JOHN DEERE', 'WWF', 'KNX', 'BCIE', 'MESSE FRANKFURT', 'MINISO',
  'GRUPO ROBLE', 'MULTIPLAZA', 'METROMALL', 'ISE BARCELONA', 'LIGHT + BUILDING',
  'PRÓSPEROS PODCAST', 'ELITE MEDICAL', 'JUAN LUCHO', 'READY BARCELONA',
]

export const BLOG_POSTS = [
  {
    slug: 'como-elegir-filmmaker-barcelona',
    date: '2026-06-01',
    read: '6 min',
    category: { es: 'Guía', en: 'Guide', ca: 'Guia' },
    cover: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/4ead92244810739.699f8377afda8.png',
    title: {
      es: 'Cómo elegir un filmmaker en Barcelona: guía completa para marcas',
      en: 'How to choose a filmmaker in Barcelona: a complete guide for brands',
      ca: 'Com triar un filmmaker a Barcelona: guia completa per a marques',
    },
    excerpt: {
      es: 'Cinco criterios clave para escoger el filmmaker adecuado para tu marca en Barcelona: portfolio, workflow, equipo, referencias y capacidad de dirección.',
      en: 'Five key criteria to choose the right filmmaker for your brand in Barcelona: portfolio, workflow, gear, references and directing skills.',
      ca: 'Cinc criteris clau per triar el filmmaker adequat per a la teva marca a Barcelona.',
    },
    content: {
      es: [
        'Elegir un filmmaker no debería empezar por preguntar “¿cuánto cuesta el vídeo?”. Para mí, la primera pregunta debería ser: ¿qué queremos comunicar y a quién queremos llegar?',
        'Barcelona es una ciudad con muchísima oferta audiovisual. Hay cámaras, productoras, creadores de contenido, editores, directores de foto y equipos completos. Pero no todos trabajan de la misma manera ni entienden igual una marca. Por eso, antes de contratar a alguien, recomiendo mirar tres cosas: su estilo visual, su forma de contar historias y su capacidad para entender el objetivo del proyecto.',
        'Un buen filmmaker no solo llega con una cámara. Llega con criterio. Sabe cuándo una escena necesita movimiento, cuándo necesita silencio, cuándo conviene un plano limpio y cuándo una marca necesita algo más humano y natural.',
        'Si eres una marca, busca a alguien que pueda explicarte el proceso con claridad: preproducción, rodaje, edición, color, sonido y entregas finales. La comunicación también es parte del trabajo.',
        'En mi caso, me gusta trabajar los proyectos desde la intención. No grabo por grabar. Antes de pulsar REC, necesito entender qué emoción queremos provocar, qué mensaje debe quedarse en la cabeza del espectador y cómo ese vídeo puede ayudar realmente a la marca.',
        'Porque al final, elegir un filmmaker en Barcelona no es solo contratar a alguien que haga vídeos bonitos. Es encontrar a alguien que sepa convertir una idea en una pieza visual con dirección, personalidad y propósito.',
      ],
    },
  },
  {
    slug: 'produccion-audiovisual-empresas',
    date: '2026-05-18',
    read: '8 min',
    category: { es: 'Estrategia', en: 'Strategy', ca: 'Estratègia' },
    cover: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400_webp/25cf46250562715.6a21c983b3eb6.jpg',
    title: {
      es: 'Producción audiovisual para empresas: qué esperar en 2026',
      en: 'Corporate video production: what to expect in 2026',
      ca: 'Producció audiovisual per a empreses: què esperar el 2026',
    },
    excerpt: {
      es: 'Del brief al máster final: cómo estructurar una producción audiovisual corporativa que combine narrativa cinematográfica y objetivos de negocio medibles.',
      en: 'From brief to final master: how to structure a corporate video production that combines cinematic narrative and measurable business goals.',
      ca: 'Com estructurar una producció audiovisual corporativa.',
    },
    content: {
      es: [
        'La producción audiovisual para empresas está cambiando. Ya no se trata solo de hacer un vídeo corporativo correcto, con planos bonitos de oficina y una música inspiradora de fondo. Hoy una empresa necesita piezas que conecten rápido, que transmitan confianza y que funcionen en diferentes plataformas.',
        'En 2026, una marca no debería pensar en “un vídeo”, sino en un sistema de contenido. Una misma producción puede convertirse en un vídeo principal para la web, clips verticales para redes sociales, piezas cortas para campañas, entrevistas, cápsulas internas y contenido para presentaciones comerciales.',
        'Para mí, una buena producción empieza mucho antes del rodaje. Empieza con preguntas: ¿qué queremos conseguir?, ¿a quién le hablamos?, ¿qué problema resolvemos?, ¿qué debe sentir la persona que vea este vídeo?',
        'Después viene la parte visual: localización, iluminación, ritmo, dirección, planos, sonido y edición. Todo debe tener una razón. No se trata de llenar el vídeo de efectos, sino de construir una pieza clara, estética y útil.',
        'Las empresas que mejor comunican no son siempre las que más presupuesto tienen. Son las que entienden que el vídeo debe estar alineado con su identidad. Un vídeo empresarial puede ser elegante, humano, cercano, premium o dinámico, pero nunca debería sentirse vacío.',
        'Mi forma de verlo es simple: una producción audiovisual bien pensada no solo muestra lo que haces. Hace que la gente entienda por qué importa.',
      ],
    },
  },
  {
    slug: 'imagen-marca-video',
    date: '2026-04-22',
    read: '5 min',
    category: { es: 'Branding', en: 'Branding', ca: 'Branding' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/160dfe228928107.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.jpg',
    title: {
      es: 'Cómo mejorar la imagen de una marca con vídeo cinematográfico',
      en: 'How to improve a brand\'s image with cinematic video',
      ca: 'Com millorar la imatge d\'una marca amb vídeo cinematogràfic',
    },
    excerpt: {
      es: 'Tres pilares para que el vídeo eleve tu marca: consistencia visual, storytelling emocional y una dirección de fotografía coherente con el posicionamiento.',
      en: 'Three pillars to make video elevate your brand: visual consistency, emotional storytelling and DoP aligned with positioning.',
      ca: 'Tres pilars perquè el vídeo elevi la teva marca.',
    },
    content: {
      es: [
        'Una marca no se construye solo con un logo, una paleta de colores o una web bonita. También se construye con la forma en la que se ve, se mueve y se siente en vídeo.',
        'El vídeo cinematográfico ayuda a elevar la percepción de una marca porque trabaja algo muy importante: la emoción visual. La luz, el encuadre, el movimiento de cámara, el ritmo de edición y el color pueden hacer que una marca se perciba más profesional, más cercana, más elegante o más aspiracional.',
        'Pero cinematográfico no significa exagerado. No todo necesita parecer una película. Para mí, el verdadero valor está en usar recursos cinematográficos con intención. Una luz suave puede transmitir confianza. Un plano detalle puede hacer que un producto parezca más cuidado. Un movimiento lento puede dar sensación de calidad. Un montaje rápido puede transmitir energía.',
        'Cuando trabajo una pieza de marca, intento pensar en cómo se verá, pero también en cómo se va a sentir. Porque una imagen bonita llama la atención, pero una imagen con intención se queda en la memoria.',
        'Mejorar la imagen de una marca con vídeo no consiste en copiar tendencias. Consiste en encontrar una estética propia y convertirla en una experiencia visual coherente.',
        'Un buen vídeo puede hacer que una marca parezca más seria, más actual y más deseable. Pero sobre todo, puede ayudar a que el público entienda quién eres antes incluso de leer una sola palabra.',
      ],
    },
  },
  {
    slug: 'errores-video-corporativo',
    date: '2026-03-14',
    read: '7 min',
    category: { es: 'Errores comunes', en: 'Common Mistakes', ca: 'Errors comuns' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/79f311247713499.Y3JvcCwxNzA0LDEzMzMsMTQ3LDA.jpg',
    title: {
      es: 'Los 7 errores más comunes en vídeos corporativos (y cómo evitarlos)',
      en: 'The 7 most common mistakes in corporate videos (and how to avoid them)',
      ca: 'Els 7 errors més comuns en vídeos corporatius',
    },
    excerpt: {
      es: 'Guiones sin arco narrativo, audio descuidado, iluminación plana... una lista práctica para no repetir los errores clásicos del vídeo corporativo.',
      en: 'Scripts without narrative arc, careless audio, flat lighting... a practical list to avoid the classic mistakes.',
      ca: 'Una llista pràctica per no repetir els errors clàssics.',
    },
    content: {
      es: [
        'He visto muchos vídeos corporativos que técnicamente están bien, pero que no conectan. Y casi siempre el problema no está en la cámara, sino en la intención.',
        'El primer error es empezar sin una idea clara. Si no sabemos qué queremos comunicar, el vídeo termina siendo una mezcla de planos bonitos sin dirección.',
        'El segundo es hablar demasiado de la empresa y poco del cliente. Una marca debe contar quién es, pero también debe mostrar qué problema resuelve y por qué eso importa.',
        'El tercer error es hacer vídeos demasiado largos. Si una pieza no mantiene la atención, da igual lo bien grabada que esté.',
        'El cuarto es descuidar el sonido. El audio malo hace que cualquier vídeo parezca menos profesional.',
        'El quinto es usar una estética genérica. Si el vídeo podría pertenecer a cualquier empresa, entonces no está transmitiendo una identidad real.',
        'El sexto es grabar sin pensar en los formatos finales. Hoy un vídeo puede necesitar versión horizontal, vertical, cortes para redes y miniaturas.',
        'Y el séptimo error es no tener una llamada a la acción clara. Después de ver el vídeo, la persona debería saber qué hacer: contactar, visitar la web, conocer un servicio o recordar una idea.',
        'Para evitar estos errores, mi recomendación es trabajar el vídeo como una pieza estratégica, no solo visual. Porque un buen vídeo corporativo no solo se ve bien. Tiene que comunicar bien.',
      ],
    },
  },
  {
    slug: 'meta-ads-anuncios',
    date: '2026-02-08',
    read: '6 min',
    category: { es: 'Publicidad', en: 'Advertising', ca: 'Publicitat' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/ef8606247708691.Y3JvcCwxMDgwLDg0NCwwLDEwMQ.jpeg',
    title: {
      es: 'Consejos para anuncios de Meta Ads que sí convierten',
      en: 'Tips for Meta Ads that actually convert',
      ca: 'Consells per a anuncis de Meta Ads que converteixen',
    },
    excerpt: {
      es: 'Hook en los primeros 3 segundos, formato vertical nativo, jerarquía visual clara y adaptación por plataforma: el checklist definitivo.',
      en: 'Hook in the first 3 seconds, native vertical format, clear visual hierarchy and per-platform adaptation.',
      ca: 'Ganxo en els primers 3 segons, format vertical natiu i jerarquia visual clara.',
    },
    content: {
      es: [
        'Un anuncio para Meta Ads no funciona igual que un vídeo de marca tradicional. En redes, la atención se gana en segundos. Por eso, el primer objetivo no es contar todo, sino conseguir que la persona no pase de largo.',
        'Para mí, un buen anuncio empieza con un gancho claro. Puede ser una pregunta, una situación reconocible, un problema directo o una imagen que despierte curiosidad. Si los primeros segundos no funcionan, el resto del vídeo casi no existe.',
        'Después viene el mensaje. Tiene que ser simple. Un anuncio no debería intentar explicar diez cosas a la vez. Mejor una idea fuerte, bien contada, que muchas ideas compitiendo entre sí.',
        'También es importante mostrar el producto o servicio en contexto. No basta con enseñar algo bonito. Hay que enseñar cómo se usa, qué cambia, qué resuelve o por qué alguien debería prestarle atención.',
        'Otro punto clave es el ritmo. Meta Ads necesita vídeos ágiles, con cortes limpios, textos en pantalla, buena composición y una estructura pensada para móvil.',
        'Mi consejo es no grabar anuncios como si fueran solo contenido publicitario. Hay que pensarlos como piezas que parecen naturales dentro del feed, pero que tienen una intención comercial clara.',
        'Un anuncio que convierte no es necesariamente el más espectacular. Es el que entiende al público, comunica rápido y hace que la siguiente acción sea fácil.',
      ],
    },
  },
  {
    slug: 'produccion-redes-sociales',
    date: '2026-01-20',
    read: '5 min',
    category: { es: 'Social Media', en: 'Social Media', ca: 'Xarxes' },
    cover: 'https://mir-s3-cdn-cf.behance.net/projects/404/4e3963250476933.Y3JvcCw1MTEzLDQwMDAsNDQzLDA.png',
    title: {
      es: 'Producción para redes sociales: el nuevo lenguaje de marca',
      en: 'Production for social media: the new brand language',
      ca: 'Producció per a xarxes socials: el nou llenguatge de marca',
    },
    excerpt: {
      es: 'Cómo diseñar un pipeline de contenido social que mantenga la calidad cinematográfica y sea sostenible en volumen mensual.',
      en: 'How to design a social content pipeline that keeps cinematic quality and is sustainable at monthly volume.',
      ca: 'Com dissenyar un pipeline de contingut social sostenible.',
    },
    content: {
      es: [
        'Las redes sociales cambiaron la manera en la que las marcas se comunican. Antes una empresa podía preparar una campaña grande y repetir el mismo mensaje durante meses. Ahora el contenido necesita ser más rápido, más humano y más adaptable.',
        'La producción para redes no significa hacer vídeos con menos calidad. Significa producir con otra lógica. Un vídeo para Instagram, TikTok o LinkedIn tiene que captar atención rápido, tener un mensaje claro y sentirse natural dentro de la plataforma.',
        'Para mí, el error más común es querer que todo parezca demasiado perfecto. En redes, lo pulido funciona, pero lo auténtico conecta. La clave está en encontrar un equilibrio: buena imagen, buen sonido, buena edición, pero sin perder cercanía.',
        'Una marca puede comunicar mucho con piezas simples: un detrás de cámaras, una explicación corta, un testimonio, un proceso, una transformación, una historia o una idea bien contada en menos de un minuto.',
        'El nuevo lenguaje de marca es más directo. Menos discurso vacío y más contenido útil. Menos “somos los mejores” y más “mira cómo podemos ayudarte”. Menos perfección forzada y más personalidad.',
        'Cuando produzco contenido para redes, intento que cada pieza tenga una función: atraer, explicar, conectar, vender o reforzar la identidad de la marca.',
        'Porque hoy una marca no solo se ve en su web. Se reconoce en cada vídeo, cada reel, cada historia y cada segundo de atención que logra ganar.',
      ],
    },
  },
]
